import React from "react";

interface ScheduleItem {
  time: string;
  activity: string;
  description?: string;
  status: "DONE" | "PENDING";
  day?: string;
}

interface SchedulePrintProps {
  schedule: ScheduleItem[];
}

export default function SchedulePrint({ schedule }: SchedulePrintProps) {
  const showDayColumn = schedule.some((item) => item.day && item.day.trim() !== "");
  
  const getStatusClass = (status: string) => {
    switch (status) {
      case "DONE":
        return "print-status-badge print-status-done";
      case "PENDING":
        return "print-status-badge print-status-pending";
      default:
        return "print-status-badge print-status-pending";
    }
  };

  const currentDate = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="print-root">
      {/* 1. Header (Repeats on Page 1, but we use table header for multi-page repetition) */}
      <div className="print-header">
        <h1 className="print-title">AI SCHEDULE / ROADMAP</h1>
        <div className="print-subtitle">Generated on {currentDate}</div>
      </div>

      {/* 2. Main Table */}
      <table className="print-table">
        <thead>
          <tr>
            {showDayColumn && <th style={{ width: "15%" }}>Day</th>}
            <th style={{ width: "15%" }}>Time</th>
            <th style={{ width: "55%" }}>Activity & Details</th>
            <th style={{ width: "15%", textAlign: "center" }}>Status</th>
          </tr>
        </thead>
        
        <tbody>
          {schedule.map((row, i) => (
            <tr key={i}>
              {showDayColumn && (
                <td className="print-day">{row.day || ""}</td>
              )}
              <td className="print-time">{row.time}</td>
              <td>
                <div className="print-activity-title">{row.activity}</div>
                {row.description && (
                  <div className="print-activity-desc">{row.description}</div>
                )}
              </td>
              <td style={{ textAlign: "center" }}>
                <span className={getStatusClass(row.status)}>{row.status}</span>
              </td>
            </tr>
          ))}
        </tbody>

        {/* 3. THE MAGIC SPACER: Reserves space at bottom of EVERY page so footer doesn't overlap */}
        <tfoot className="print-table-footer">
          <tr>
            <td colSpan={showDayColumn ? 4 : 3}>
              <div className="print-footer-space"></div>
            </td>
          </tr>
        </tfoot>
      </table>

      {/* 4. The Fixed Footer Content (Floats into the space reserved above) */}
      <div className="print-footer">
        <div className="print-footer-content">
          <span>Generated by EduGenie AI</span>
          <span className="mx-2">•</span>
          <span>Total Activities: {schedule.length}</span>
          <span className="mx-2">•</span>
          <span>Keep pushing forward! 🚀</span>
        </div>
      </div>
    </div>
  );
}